---measure by dimention = magnitude---

--- find total customers by gender---
select 
country,
count(customer_key) as total_customer
from gold.dim_customers
group by country
order by total_customer desc

--find toal customers by gender--
select 
gender,
count(customer_key) as total_customer
from gold.dim_customers
group by gender 
order by total_customer desc

---find total products by category---
select 
category,
count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc

---what is the average cost in each category---
select 
category,
round(avg(cost),2) as avg_cost
from gold.dim_products
group by category
order by 2 desc

---what is the total revenue generated for each category---
select 
sum(f.sales_amount) total_revenue , p.category
from gold.fact_sales f
left join gold.dim_products P
on p.product_key = f.product_key
group by p.category
order by total_revenue desc

---what is the total revenue generated by each customer---

select 
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by
1,2,3
order by total_revenue desc


--what is the distribution of sold items across countries--

select 
c.country,
sum(f.sales_amount) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by
1
order by total_sold_items desc
